#
# Module manifest for module 'WorkflowManagerDsc'
#
# Generated by: Nik Charlebois
#
# Generated on: 2019/06/17
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.3.1.0'

# ID used to uniquely identify this module
GUID = '08bb95ed-7597-4501-8d56-2724687c9768'

# Author of this module
Author = 'Ilian Nilsson'

# Company or vendor of this module
CompanyName = 'Visity AB'

# Copyright statement for this module
Copyright = '(c) 2019 Visity AB. All rights reserved.'

# Description of the functionality provided by this module
Description = 'The WorkflowManagerDsc module provides the ability to install and configure a Workflow Manager Farm.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @("modules\WorkflowManagerDsc.Util\WorkflowManagerDSC.Util.psm1")

# Functions to export from this module
# FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = @('Get-WmfDscInstalledProductVersion')

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/IlleNilsson/WorkflowManagerDsc/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/IlleNilsson/WorkflowManagerDsc'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
        ## 1.3.1

        * WorkflowManagerInstall
          * Workaround for faulty references to Microsoft.ServiceBus.dll, 1.8.0.0 
          in WorkflowManager PowerShell module.
        ## 1.3

        * WorkflowManagerInstall
          * Added ability to install Workflow Manager Refresh package (including
            CU4), CU5 and Service Bus v1.1 with TLS 1.2 update.

        ## 1.2.0.1

        * WorkflowManagerFarm
          * Corrected small issue in schema that was added during previous change.

        ## 1.2

        * WorkflowManagerFarm
          * Added ability to specify custom database names
          * Corrected cmdlet parameters to make sure the farm is actually using
            the specified credentials

        ## 1.1.0.1

        * WorkflowManagerFarm
          * Updated resource to make sure the Windows Environment
            variables are loaded into the PowerShell session
          * Fixed typo in Get method where it returned an incorrectly
            named property

        ## 1.1

        * WorkflowManagerInstall
          * Added ability to install the Workflow Manager Client only
          * Added check to unblock setup file if it is blocked because it is coming
            from a network location. This to prevent endless wait
          * Added ability to install from a UNC path, by adding server
            to IE Local Intranet Zone. This will prevent an endless wait
            caused by security warning

        ## 1.0

        * Initial Release;
        '

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
