
[ClassVersion("1.0.0.0"), FriendlyName("WorkflowManagerInstall")]
class MSFT_WorkflowManagerInstall : OMI_BaseResource
{
    [Key, Description("Set to 'present' to specificy that the product should be installed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Path to WebpiCmd.exe")] String WebPIPath;
    [Required, Description("Path to Feeds XML")] String XMLFeedPath;
};
